const datacfContact = {
  data: {
    success: true,
    msg: 'Data Found Successfully',
    data: [
      {
        MapURL: 'https://maps.google.com/maps?q=501, 5th\nFloor, Smeet, above Trends, Sarabhai Campus,, nan, Near Genda Circle, Gorwa Road, Vadodara, 390023&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>501, 5th Floor, Smeet, above Trends, Sarabhai Campus,</p>\n',
            streetName: null,
            landmark: 'Near Genda Circle',
            AreaName: 'Gorwa Road',
            city: 'Vadodara',
            pincode: '390023',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=501, 5th\nFloor, Smeet, above Trends, Sarabhai Campus,, nan, Near Genda Circle, Gorwa Road, Vadodara, 390023&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=2nd Floor JK Plaza, Gast Ka Tazia ,, nan, Falka Bazara,, Lashkar, Gwalior, 474001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>2nd Floor JK Plaza, Gast Ka Tazia,</p>\n',
            streetName: null,
            landmark: 'Falka Bazara,',
            AreaName: 'Lashkar',
            city: 'Gwalior',
            pincode: null,
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=2nd Floor JK Plaza, Gast Ka Tazia ,, nan, Falka Bazara,, Lashkar, Gwalior, 474001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=1011, 1 st\nFloor\n,Avinashi Road, Above IDFC Bank, Coimbatore- 641018, Avinashi Road, Above IDFC Bank, Tamil Nadu, Coimbatore, 641018&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
            buildingName: '<p>1011, 1 st Floor, Avinashi Road, Above IDFC Bank, Coimbatore- 641018, Avinashi Road, Above IDFC Bank, Tamil Nadu, Coimbatore, 641018</p>\n',
            streetName: null,
            landmark: 'Above IDFC Bank',
            AreaName: 'Tamil Nadu',
            city: 'Coimbatore',
            pincode: '641018',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=1011, 1 st\nFloor\n,Avinashi Road, Above IDFC Bank, Coimbatore- 641018, Avinashi Road, Above IDFC Bank, Tamil Nadu, Coimbatore, 641018&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=CTS NO 3935-36, MG\nTower, 1st Floor,, Club Road,, Opp Gov Civil Hospital,, nan, Belgaum, 590001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>CTS NO 3935-36, MG Tower, 1st Floor,</p>\n',
            streetName: null,
            landmark: 'Opp Gov Civil Hospital,',
            AreaName: null,
            city: 'Belgaum',
            pincode: '590001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=CTS NO 3935-36, MG\nTower, 1st Floor,, Club Road,, Opp Gov Civil Hospital,, nan, Belgaum, 590001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=First Floor, SCO-38,, nan, PUDA\nComplex,, nan, Jalandhar, 144001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>First Floor, SCO-38,</p>\n',
            streetName: null,
            landmark: 'PUDA Complex,',
            AreaName: null,
            city: 'Jalandhar',
            pincode: '144001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=First Floor, SCO-38,, nan, PUDA\nComplex,, nan, Jalandhar, 144001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Leela Towers, 2nd floor\nNo.53/2520, K,L, Subhash Chandra Bose Road,, Jawahar Nagar Avenue,, Ernakulam,, Kochi, 682019&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
            buildingName: '<p>Leela Towers, 2nd floor No.53/2520</p>\n',
            streetName: null,
            landmark: 'Jawahar Nagar Avenue',
            AreaName: 'Ernakulam',
            city: 'Kochi',
            pincode: '682019',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Leela Towers, 2nd floor\nNo.53/2520, K,L, Subhash Chandra Bose Road,, Jawahar Nagar Avenue,, Ernakulam,, Kochi, 682019&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=UGF-2,\nCenter Court,, 5 Park Road,, Center Court,, nan, Lucknow, 226001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '9105224048416',
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '9105224048416',
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>UGF-2, Center Court,</p>\n',
            streetName: null,
            landmark: 'Center Court,',
            AreaName: null,
            city: 'Lucknow',
            pincode: '226001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=UGF-2,\nCenter Court,, 5 Park Road,, Center Court,, nan, Lucknow, 226001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=ALPS\nBuilding,, Central Block,, nan, 1st Floor, 56 Janpath,, New Delhi, 110,001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>ALPS Building,</p>\n',
            streetName: null,
            landmark: null,
            AreaName: '1st Floor, 56 Janpath,',
            city: 'New Delhi',
            pincode: '110001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=ALPS\nBuilding,, Central Block,, nan, 1st Floor, 56 Janpath,, New Delhi, 110,001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Motilal Oswal Mutual Fund,, Nexus Point Building,, Beside NMC office, Civil Lines,, Nagpur, 440001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>Motilal Oswal Mutual Fund,</p>\n',
            streetName: null,
            landmark: 'Beside NMC office',
            AreaName: 'Civil Lines',
            city: 'Nagpur',
            pincode: '440001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Motilal Oswal Mutual Fund,, Nexus Point Building,, Beside NMC office, Civil Lines,, Nagpur, 440001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Shop No. 2, M/s Advani Enterprises,, Dr. A B Road,, Cabin No CU- 07,NeelKamal Arcade,, Goa, Panaji, 403,001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
            buildingName: '<p>Shop No. 2, M/s Advani Enterprises,</p>\n',
            streetName: null,
            landmark: 'Cabin No CU- 07,NeelKamal Arcade,',
            AreaName: 'Goa',
            city: 'Panaji',
            pincode: '403001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Shop No. 2, M/s Advani Enterprises,, Dr. A B Road,, Cabin No CU- 07,NeelKamal Arcade,, Goa, Panaji, 403,001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=2 nd Floor, Rockford Business Centre,, Ring Road, Udhana\nDarwaja,, nan, nan, Surat, 395001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912613915004',
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912613915004',
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>2 nd Floor, Rockford Business Centre,</p>\n',
            streetName: null,
            landmark: null,
            AreaName: null,
            city: 'Surat',
            pincode: '395001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=2 nd Floor, Rockford Business Centre,, Ring Road, Udhana\nDarwaja,, nan, nan, Surat, 395001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3662.817389623861!2d85.325839!3d23.3586295!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39f4e1bddc29ac4d%3A0xc4878bc04a34a0d4!2sMotilal%20Oswal%20Financial%20Services%20Limited!5e0!3m2!1sen!2sin!4v1760608623422!5m2!1sen!2sin',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
            buildingName: '<p>59, 2nd Floor,</p>\n',
            streetName: null,
            landmark: null,
            AreaName: 'Ranchi',
            city: 'Ranchi',
            pincode: '834001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3662.817389623861!2d85.325839!3d23.3586295!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39f4e1bddc29ac4d%3A0xc4878bc04a34a0d4!2sMotilal%20Oswal%20Financial%20Services%20Limited!5e0!3m2!1sen!2sin!4v1760608623422!5m2!1sen!2sin',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=1289, 4th\nFloor , Office No 401,, nan, Hotel Paras\n,Opp. Manas Bhawan,, Wright Town,, Jabalpur, 482002&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>1289, 4th Floor , Office No 401,</p>\n',
            streetName: null,
            landmark: 'Hotel Paras ,Opp. Manas Bhawan,',
            AreaName: 'Wright Town,',
            city: 'Jabalpur',
            pincode: '482002',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=1289, 4th\nFloor , Office No 401,, nan, Hotel Paras\n,Opp. Manas Bhawan,, Wright Town,, Jabalpur, 482002&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3887.7701714157247!2d77.5806376!3d12.986546499999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae161435458edf%3A0x5f0d7408a99ffe4c!2sMotilal%20Oswal%20Tower%20-%20Regional%20Headquarters!5e0!3m2!1sen!2sin!4v1759927507450!5m2!1sen!2sin',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>Motilal Oswal Tower,</p>\n',
            streetName: null,
            landmark: 'Opp. To Karnataka Film Chambers,',
            AreaName: 'Kumarapark East, Seshadripuram,',
            city: 'Bangalore',
            pincode: '560001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3887.7701714157247!2d77.5806376!3d12.986546499999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae161435458edf%3A0x5f0d7408a99ffe4c!2sMotilal%20Oswal%20Tower%20-%20Regional%20Headquarters!5e0!3m2!1sen!2sin!4v1759927507450!5m2!1sen!2sin',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=10th Floor, Motilal Oswal Tower,, Rahimtullah Sayani Road,, Opposite Parel ST Depot,, Prabhadevi,, Mumbai, 400,025&output=embed',
        contactDet: [
          {
            officeName: 'Registered & Corporate Office : Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Registered & Corporate Office : Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>10th Floor, Motilal Oswal Tower,</p>\n',
            streetName: null,
            landmark: 'Opposite Parel ST Depot,',
            AreaName: 'Prabhadevi,',
            city: 'Mumbai',
            pincode: '400025',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=10th Floor, Motilal Oswal Tower,, Rahimtullah Sayani Road,, Opposite Parel ST Depot,, Prabhadevi,, Mumbai, 400,025&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://www.google.com/maps/search/?api=1&query=Wing%20B%2C%203rd%20Floor%2C%0AConstantia%20Building%2C%2C%2011%2C%20Dr.%20U.N%0ABramachari%20Street%2C%2C%20nan%2C%20Kolkata%2C%20Kolkata%2C%20700%2C017',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '913366077238',
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '913366077238',
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>Wing B, 3rd Floor, Constantia Building,</p>\n',
            streetName: null,
            landmark: null,
            AreaName: 'Kolkata',
            city: null,
            pincode: '700017',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://www.google.com/maps/search/?api=1&query=Wing%20B%2C%203rd%20Floor%2C%0AConstantia%20Building%2C%2C%2011%2C%20Dr.%20U.N%0ABramachari%20Street%2C%2C%20nan%2C%20Kolkata%2C%20Kolkata%2C%20700%2C017',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=1st Floor Anant Complex,, nan, Handloom House, Sigra,, Varanasi, 221010&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>1st Floor Anant Complex,</p>\n',
            streetName: null,
            landmark: 'Handloom House',
            AreaName: 'Sigra,',
            city: 'Varanasi',
            pincode: '221010',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=1st Floor Anant Complex,, nan, Handloom House, Sigra,, Varanasi, 221010&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Office No. 401, 4th\nFloor, Millenium Tower,, CTS No.\n885/1, Plot No. 241/1/A,, Opp Kotak Bank, Bhandarkar Road,, Shivaji Nagar, Pune, 411004&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '2066474300',
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '2066474300',
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>Office No. 401, 4th Floor, Millenium Tower,</p>\n',
            streetName: null,
            landmark: 'Opp Kotak Bank, Bhandarkar Road,',
            AreaName: 'Shivaji Nagar',
            city: 'Pune',
            pincode: '411004',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Office No. 401, 4th\nFloor, Millenium Tower,, CTS No.\n885/1, Plot No. 241/1/A,, Opp Kotak Bank, Bhandarkar Road,, Shivaji Nagar, Pune, 411004&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Piyank Tower, 3rd Floor, Raja Talab Road,, nan, Ward No. 40,, Raipur, 492\n001.&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
            buildingName: '<p>Piyank Tower, 3rd Floor</p>\n',
            streetName: null,
            landmark: null,
            AreaName: 'Ward No. 40',
            city: 'Raipur',
            pincode: '492001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Piyank Tower, 3rd Floor, Raja Talab Road,, nan, Ward No. 40,, Raipur, 492\n001.&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=1st Floor, Ganapati Enclave,, Ulubari, GS Road,, nan, East Guwahati, Guwahati, 781007&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>1st Floor, Ganapati Enclave,</p>\n',
            streetName: null,
            landmark: null,
            AreaName: 'East Guwahati',
            city: 'Guwahati',
            pincode: '781007',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=1st Floor, Ganapati Enclave,, Ulubari, GS Road,, nan, East Guwahati, Guwahati, 781007&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=501/502, 5th\nFloor,, Sharanpur Road, Laxmi\nEnclave,, Old Pandit Colony, Off, Nasik, 22002&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
            buildingName: '<p>501/502, 5th Floor,</p>\n',
            streetName: null,
            landmark: 'Laxmi Enclave,',
            AreaName: 'Old Pandit Colony, Off',
            city: 'Nasik',
            pincode: '22002',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=501/502, 5th\nFloor,, Sharanpur Road, Laxmi\nEnclave,, Old Pandit Colony, Off, Nasik, 22002&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=First floor, 7- 3-A1,, MG Marg, Civil lines,, Above pizza hut(near Indian coffee house), nan, Prayagraj, 211001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal oswal financial services,',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal oswal financial services,',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>First floor, 7- 3-A1,</p>\n',
            streetName: null,
            landmark: 'Above pizza hut(near Indian coffee house)',
            AreaName: null,
            city: 'Prayagraj',
            pincode: '211001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=First floor, 7- 3-A1,, MG Marg, Civil lines,, Above pizza hut(near Indian coffee house), nan, Prayagraj, 211001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=New No.3,\nOld No.2,3rd Floor,, Club House Road,, Next to Hotel Taj Club House,, Anna Salai,, Chennai, 600002&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '2240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '2240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
            buildingName: '<p>New No.3, Old No.2,3rd Floor,</p>\n',
            streetName: null,
            landmark: 'Next to Hotel Taj Club House,',
            AreaName: 'Anna Salai,',
            city: 'Chennai',
            pincode: '600002',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=New No.3,\nOld No.2,3rd Floor,, Club House Road,, Next to Hotel Taj Club House,, Anna Salai,, Chennai, 600002&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3889.525981196602!2d74.84887122483963!3d12.873863887432575!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba35b16dc53b8e7%3A0xd36b85ebae22bd61!2sMotilal%20Oswal%20Financial%20Services%20Limited!5e0!3m2!1sen!2sin!4v1760106594375!5m2!1sen!2sin',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>Unit 13,14 and 15, 3rd floor, Milestone-25,</p>\n',
            streetName: null,
            landmark: 'Land Trades Builders & Developers,',
            AreaName: 'Balmatta,',
            city: 'Mangalore',
            pincode: '575001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3889.525981196602!2d74.84887122483963!3d12.873863887432575!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba35b16dc53b8e7%3A0xd36b85ebae22bd61!2sMotilal%20Oswal%20Financial%20Services%20Limited!5e0!3m2!1sen!2sin!4v1760106594375!5m2!1sen!2sin',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=2nd Floor, Sai square building,, Bhargava Estate,, nan, Civil Lines,, Kanpur, 208001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>2nd Floor, Sai square building,</p>\n',
            streetName: null,
            landmark: null,
            AreaName: 'Civil Lines,',
            city: 'Kanpur',
            pincode: '208001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=2nd Floor, Sai square building,, Bhargava Estate,, nan, Civil Lines,, Kanpur, 208001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Fortune Chambers, SCO:16-17,\n4th Floor,, nan, Feroze Gandhi Market,, nan, Ludhiana, 141,001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>Fortune Chambers, SCO:16-17, 4th Floor,</p>\n',
            streetName: null,
            landmark: 'Feroze Gandhi Market,',
            AreaName: null,
            city: 'Ludhiana',
            pincode: '141001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Fortune Chambers, SCO:16-17,\n4th Floor,, nan, Feroze Gandhi Market,, nan, Ludhiana, 141,001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Office No : SF -6,\nSecond floor, SCO -5,, nan, District\nShopping complex,B Block,, Ranjit Avenue,, Amritsar, 143001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>Office No : SF -6, Second floor, SCO -5,</p>\n',
            streetName: null,
            landmark: 'District Shopping complex,B Block, ',
            AreaName: 'Ranjit Avenue,',
            city: 'Amritsar',
            pincode: '143001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Office No : SF -6,\nSecond floor, SCO -5,, nan, District\nShopping complex,B Block,, Ranjit Avenue,, Amritsar, 143001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Shantiniketan Building, 2nd floor above\nIDBI Bank,, Bistupur, nan, Jamshedpur, Jamshedpur, 831,001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '8108622222',
            emailid: null,
            links: null,
            buildingName: '<p>Shantiniketan Building, 2nd floor above IDBI Bank,</p>\n',
            streetName: null,
            landmark: null,
            AreaName: 'Jamshedpur',
            city: 'Jamshedpur',
            pincode: '831001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Shantiniketan Building, 2nd floor above\nIDBI Bank,, Bistupur, nan, Jamshedpur, Jamshedpur, 831,001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3548.653397893695!2d78.00116379678953!3d27.1986284!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x397477ea6c4edf21%3A0xbed1c7b2fde6a9bb!2sMotilal%20Oswal%20Financial%20Services%20Limited!5e0!3m2!1sen!2sin!4v1761743109436!5m2!1sen!2sin',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>F-03 &amp; F-03A, First Floor, Friends Wasan Plaza,</p>\n',
            streetName: null,
            landmark: 'Above HDFC Bank,',
            AreaName: 'Sanjay Place,',
            city: 'Agra',
            pincode: '282002',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3548.653397893695!2d78.00116379678953!3d27.1986284!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x397477ea6c4edf21%3A0xbed1c7b2fde6a9bb!2sMotilal%20Oswal%20Financial%20Services%20Limited!5e0!3m2!1sen!2sin!4v1761743109436!5m2!1sen!2sin',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=SCO 44 -45,\n2nd Floor, Sector 9 D,, nan, nan, Above PNB Bank, Chandigarh, 160017&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>SCO 44 -45, 2nd Floor, Sector 9 D,</p>\n',
            streetName: null,
            landmark: null,
            AreaName: 'Above PNB Bank',
            city: 'Chandigarh',
            pincode: '160017',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=SCO 44 -45,\n2nd Floor, Sector 9 D,, nan, nan, Above PNB Bank, Chandigarh, 160017&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=505A &\n505B,504\nand 506B, 5th Floor, Ashiana Plaza,, Budh Marg,, nan, nan, Patna, 800001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>505A and 505B,504 and 506B, 5th Floor, Ashiana Plaza,</p>\n',
            streetName: null,
            landmark: null,
            AreaName: null,
            city: 'Patna',
            pincode: '800001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=505A &\n505B,504\nand 506B, 5th Floor, Ashiana Plaza,, Budh Marg,, nan, nan, Patna, 800001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3476.494032744599!2d76.97152659999999!3d29.385100599999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ddb02470a3971%3A0xa0f55372f7c23b0c!2sMotilal%20Oswal%20Financial%20Services%20Limited!5e0!3m2!1sen!2sin!4v1760608247955!5m2!1sen!2sin',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>N K Tower, 1st floor,</p>\n',
            streetName: null,
            landmark: 'Next to Hive Hotel,',
            AreaName: null,
            city: 'Panipat',
            pincode: '132103',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3476.494032744599!2d76.97152659999999!3d29.385100599999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ddb02470a3971%3A0xa0f55372f7c23b0c!2sMotilal%20Oswal%20Financial%20Services%20Limited!5e0!3m2!1sen!2sin!4v1760608247955!5m2!1sen!2sin',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=4 th and 5th Floor, KJ City Tower,, Ashok Marg,, nan, C-Scheme Jaipur,, Jaipur, 302001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '918108622222',
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '912240548002',
            mobileNo: '918108622222',
            emailid: null,
            links: null,
            buildingName: '<p>4 th and 5th Floor, KJ City Tower,</p>\n',
            streetName: null,
            landmark: null,
            AreaName: 'C-Scheme Jaipur,',
            city: 'Jaipur',
            pincode: '302001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=4 th and 5th Floor, KJ City Tower,, Ashok Marg,, nan, C-Scheme Jaipur,, Jaipur, 302001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=6th Floor,\n607 to 610,\nMajestic Building,, BRTS, Near Law Garden,, nan, Ahmedabad, 380009&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>6th Floor, 607 to 610, Majestic Building,</p>\n',
            streetName: null,
            landmark: 'Near Law Garden,',
            AreaName: null,
            city: 'Ahmedabad',
            pincode: '380009',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=6th Floor,\n607 to 610,\nMajestic Building,, BRTS, Near Law Garden,, nan, Ahmedabad, 380009&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7651.076321504731!2d80.6465516943706!3d16.49890697408485!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a35fac7d0ee5ee5%3A0xbc0d825a2ab94a0f!2sMotilal%20Oswal%20Financial%20Services%20Limited!5e0!3m2!1sen!2sin!4v1759926636005!5m2!1sen!2sin',
        contactDet: [
          {
            officeName: 'Motilal Oswal AMC - RM',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal AMC - RM',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>#2nd Floor, 59-13-2-1, Gayatri Nagar,</p>\n',
            streetName: null,
            landmark: 'Polytechnic Post,',
            AreaName: null,
            city: 'Vijayawada',
            pincode: '520008',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7651.076321504731!2d80.6465516943706!3d16.49890697408485!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a35fac7d0ee5ee5%3A0xbc0d825a2ab94a0f!2sMotilal%20Oswal%20Financial%20Services%20Limited!5e0!3m2!1sen!2sin!4v1759926636005!5m2!1sen!2sin',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Unit No.\n1024 to Unit\nNo. 1029,\n10th Floor,, nan, R K Empire, Mavdi Bridge,, nan, Rajkot, nan&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>Unit No. 1024 to Unit No. 1029, 10th Floor,</p>\n',
            streetName: null,
            landmark: 'R K Empire, Mavdi Bridge,',
            AreaName: null,
            city: 'Rajkot',
            pincode: null,
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Unit No.\n1024 to Unit\nNo. 1029,\n10th Floor,, nan, R K Empire, Mavdi Bridge,, nan, Rajkot, nan&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=202 & 203,\n2nd Floor, Sri Ram Plaza,\nBank More,, nan, nan, nan, Dhanbad, 826001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>202 and 203, 2nd Floor, Sri Ram Plaza, Bank More,</p>\n',
            streetName: null,
            landmark: null,
            AreaName: null,
            city: 'Dhanbad',
            pincode: '826001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=202 & 203,\n2nd Floor, Sri Ram Plaza,\nBank More,, nan, nan, nan, Dhanbad, 826001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Ground Floor, shop no 4 NCR Plaza,, Bearing Municipal no 54 A New\nCantt Road,, New Municipal No 115-88,\nRavindra Nath Tagore Marg Hathibarkala,, Hathibarkala,, Dehradun, 248001&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>Ground Floor, shop no 4 NCR Plaza,</p>\n',
            streetName: null,
            landmark: 'New Municipal No 115-88, Ravindra Nath Tagore Marg Hathibarkala,',
            AreaName: 'Hathibarkala,',
            city: 'Dehradun',
            pincode: '248001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Ground Floor, shop no 4 NCR Plaza,, Bearing Municipal no 54 A New\nCantt Road,, New Municipal No 115-88,\nRavindra Nath Tagore Marg Hathibarkala,, Hathibarkala,, Dehradun, 248001&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Office No 1, 2nd Floor , Vidya Tower, Above HDFC Bank,, Pratap Nagar Road,, Above HDFC Bank, Near Aakhliya Circle,, nan, Jodhpur, 342003&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>Office No 1, 2nd Floor , Vidya Tower, Above HDFC Bank,</p>\n',
            streetName: null,
            landmark: 'Above HDFC Bank, Near Aakhliya Circle,',
            AreaName: null,
            city: 'Jodhpur',
            pincode: '342003',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Office No 1, 2nd Floor , Vidya Tower, Above HDFC Bank,, Pratap Nagar Road,, Above HDFC Bank, Near Aakhliya Circle,, nan, Jodhpur, 342003&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=2 nd Floor Shagun\nArcade, Vijay Nagar Crossing, nan, nan, Indore, 452010&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '9713233261',
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '9713233261',
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>2 nd Floor Shagun Arcade</p>\n',
            streetName: null,
            landmark: null,
            AreaName: null,
            city: 'Indore',
            pincode: '452010',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=2 nd Floor Shagun\nArcade, Vijay Nagar Crossing, nan, nan, Indore, 452010&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=R-11, 3RD\nFloor, Hardev Complex, nan, Besides IDBI Branch, Zone-2, MP, Bhopal, 462011&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>R-11, 3RD Floor, Hardev Complex</p>\n',
            streetName: null,
            landmark: 'Besides IDBI Branch',
            AreaName: 'Zone-2, MP',
            city: 'Bhopal',
            pincode: '462011',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=R-11, 3RD\nFloor, Hardev Complex, nan, Besides IDBI Branch, Zone-2, MP, Bhopal, 462011&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Radhika Elite, 2nd Floor,\nPlot No. 480,, nan, Above SBI,, Bomikhal, Rasulgarh,, Bhubaneswar, 751010&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>Radhika Elite, 2nd Floor, Plot No. 480,</p>\n',
            streetName: null,
            landmark: 'Above SBI,',
            AreaName: 'Bomikhal, Rasulgarh,',
            city: 'Bhubaneswar',
            pincode: '751010',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Radhika Elite, 2nd Floor,\nPlot No. 480,, nan, Above SBI,, Bomikhal, Rasulgarh,, Bhubaneswar, 751010&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=Pakki’s , Office No 302, 2nd\nFloor,, nan, Plot No.\n214B, T. S. No. 674,, Dwarakanagar,, Visakhapatnam, 530016&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>Pakki’s , Office No 302, 2nd Floor,</p>\n',
            streetName: null,
            landmark: 'Plot No. 214B, T. S. No. 674',
            AreaName: 'Dwarakanagar,',
            city: 'Visakhapatnam',
            pincode: '530016',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=Pakki’s , Office No 302, 2nd\nFloor,, nan, Plot No.\n214B, T. S. No. 674,, Dwarakanagar,, Visakhapatnam, 530016&output=embed',
          },
        ],
      },
      {
        MapURL: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3562.7049510397574!2d83.36415!3d26.75379!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39914531e69eb661%3A0x7d3d3e495877a8e1!2sMotilal%20Oswal%20Financial%20Services%20Limited!5e0!3m2!1sen!2sin!4v1760608809251!5m2!1sen!2sin',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: null,
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>No 1st Floor,</p>\n',
            streetName: null,
            landmark: 'Near Jubilee Inter College,',
            AreaName: null,
            city: 'Gorakhpur',
            pincode: '273001',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3562.7049510397574!2d83.36415!3d26.75379!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39914531e69eb661%3A0x7d3d3e495877a8e1!2sMotilal%20Oswal%20Financial%20Services%20Limited!5e0!3m2!1sen!2sin!4v1760608809251!5m2!1sen!2sin',
          },
        ],
      },
      {
        MapURL: 'https://maps.google.com/maps?q=3th Floor, Door No- 6-3-670,, nan, RKJSM\nSquares, Above Reliance\nDigital, Near Hyderabad Central, Punjagutta,, Hyderabad, 500082&output=embed',
        contactDet: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '9104061405035',
            mobileNo: null,
            emailid: null,
            links: null,
          },
        ],
        contactAdd: [
          {
            officeName: 'Motilal Oswal Asset Management Company Ltd.',
            landlineNo: '9104061405035',
            mobileNo: null,
            emailid: null,
            links: null,
            buildingName: '<p>3th Floor, Door No- 6-3-670,</p>\n',
            streetName: null,
            landmark: 'RKJSM Squares, Above Reliance Digital, Near Hyderabad Central',
            AreaName: 'Punjagutta,',
            city: 'Hyderabad',
            pincode: '500082',
            iscorporateOffice: 0,
            notes: null,
            mapIframe: 'https://maps.google.com/maps?q=3th Floor, Door No- 6-3-670,, nan, RKJSM\nSquares, Above Reliance\nDigital, Near Hyderabad Central, Punjagutta,, Hyderabad, 500082&output=embed',
          },
        ],
      },
    ],
  },
  isSecureResponseReqd: false,
};
export default datacfContact;
